require:
  - rubocop-rails

inherit_mode:
  merge:
    - Include

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'

Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Max: 14

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
  Exclude:
    - 'spec/**/*'
